

POST http://localhost:9090/soap/sakila/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://soap.service.jets.iti.gov/">
    <soap:Body>
        <jets:FindAllInventory>
        </jets:FindAllInventory>
    </soap:Body>
</soap:Envelope>

###


POST http://localhost:9090/soap/sakila/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:jets="http://soap.service.jets.iti.gov/">
    <soap:Body>
        <jets:FindInventoryById>
            <InventoryId>1</InventoryId>
        </jets:FindInventoryById>
    </soap:Body>
</soap:Envelope>
